# Generated by Django 3.2.5 on 2021-07-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='domain_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
