# Generated by Django 3.2.5 on 2021-07-12 10:42

from django.db import migrations
import reviews.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20210711_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=reviews.fields.IntegerRangeField(),
        ),
    ]
